FROM phpdockerio/php:8.2-fpm
WORKDIR "/var/www/html"

RUN apt-get update \
    && apt-get -y --no-install-recommends install \
        php8.2-bz2 \ 
        php8.2-gd \ 
        php8.2-gmagick \ 
        php8.2-http \ 
        php8.2-igbinary \ 
        php8.2-imap \ 
        php8.2-mcrypt \ 
        php8.2-memcache \ 
        php8.2-memcached \ 
        php8.2-mysql \ 
        php8.2-redis \ 
        php8.2-snmp \ 
        php8.2-soap \ 
        php8.2-xdebug \ 
        php8.2-yaml \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

RUN apt-get update && apt-get install -y supervisor




COPY ./phpdocker/php-fpm/supervisord/* /etc/supervisor/

COPY ./ /var/www/html

CMD ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
