name: PHP PSR-12 Validator

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Composer dependencies
        run: composer install --no-scripts --no-progress --no-suggest --prefer-dist

      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Check PHP coding standards (PSR-12)
        run: ~/.composer/vendor/bin/phpcs --standard=PSR12 Controllers/* Libraries/* Models/* autoload.php index.php
