name: Build and Push Docker Images

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
  
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml up -d
        working-directory: ./

      - name: Wait for services to start
        run: |
          docker images
          sleep 10

      - name: Install Composer dependencies
        run: composer install


      - name: Tag and Push Memcached image
        run: |
          docker tag memcached:alpine jmtalves/mso-user:memcached
          docker push jmtalves/mso-user:memcached
        working-directory: ./

      - name: Tag and Push Nginx image
        run: |
          docker tag nginx:alpine jmtalves/mso-user:nginx
          docker build  -f ./phpdocker/nginx/Dockerfile -t jmtalves/mso-user:nginx .
          docker push jmtalves/mso-user:nginx
        working-directory: ./


      - name: Tag and Push PHP-FPM image
        working-directory: ./
        run: |
          docker tag mso-users_php-fpm:latest jmtalves/mso-user:php-fpm
          docker build  -f ./phpdocker/php-fpm/Dockerfile -t jmtalves/mso-user:php-fpm . 
          docker push jmtalves/mso-user:php-fpm
        
